name: LeeesTpsMonitor
version: 1.0.0
main: Leees.Chat.Whitelist.Main
api-version: 1.13
authors: [Nate, Legault]
description: tps monitor plugin
website: http://6b6t.org
commands:
  ltmreload:
    permission: ltm.admin
